### ISSUE TITLE
Is not working it gives just a list of names

### ISSUE THREAD

**Issue by Jummp** [lazargugleta/instagramUnfollowers#10]
hey! I was trying your code. but isn't working, I am new from github, can you help me?

Continue...
Accessing profile...
Getting following people, this might take a while...
[15532:14972:1215/153700.345:ERROR:gpu_init.cc(523)] Passthrough is not supported, GL is disabled, ANGLE is 
Got one list of: 318
Getting followers, this might take a while...
Got one list of: 0
These people are not following you:

*random list of names*

**Comment by lazargugleta** [comment]
Could you provide the environment you are using?
[This](https://stackoverflow.com/a/67578811) is the first solution I found on the web so maybe take a look at that.
It is probably local setup problem.
